name: Publish Superfluid Token List package to NPM
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build package
        run: pnpm --filter @superfluid-finance/tokenlist build
      - name: Publish package
        run: pnpm --filter @superfluid-finance/tokenlist publish --access public --no-git-checks
